### ISSUE TITLE
how to use the requirement

### ISSUE THREAD

**Issue by fsted** [DongSky/lbba_boosted_wsod#1]
I try to install environment by pip install -r requirement，but it's error.

**Comment by DongSky** [comment]
Hi fsted.
This requirement file is exported from the anaconda virtual environment. Therefore you can use the command below to create the corresponding environment via anaconda / miniconda:
```shell
conda create --name <env> --file <this file>
```
Similarly, you can simply create the training environment following the two reference project mentioned in readme.txt, and make sure that the version of pytorch is 1.1.0 or 1.2.0.

**Comment by HMCCMH** [comment]
I used the anaconda. However, it made an error. 
```
ERROR: Invalid requirement: '_libgcc_mutex=0.1=main' (from line 4 of lbba_requirements.txt)
Hint: = is not a valid operator. Did you mean == ?
```

**Comment by DongSky** [comment]
> I used the anaconda. However, it made an error.
> 
> ```
> ERROR: Invalid requirement: '_libgcc_mutex=0.1=main' (from line 4 of lbba_requirements.txt)
> Hint: = is not a valid operator. Did you mean == ?
> ```

Hi HMCCMH
We provide two solutions.
1) install pytorch, numpy, easydict and opencv manually with conda install. Since most of packages in the config file will be installed automatically, you can focus on these core packages. 
2) I uploaded a new config file, and the line including libgcc is deleted.

**Comment by HMCCMH** [comment]
> 

Sorry, I see the config file updated 7 months ago. The line including libgcc is existing.

**Comment by HMCCMH** [comment]
And PyTorch 1.2.0  now is only used for CUDA10.0 in the [web](https://download.pytorch.org/whl/torch_stable.html)

**Comment by DongSky** [comment]
> > 
> 
> Sorry, I see the config file updated 7 months ago. The line including libgcc is existing.

Hi HMCCMH
1) the new config file is here https://github.com/DongSky/lbba_boosted_wsod/blob/master/lbba.yml
2) About CUDA version, I found that my workstation installed both CUDA 10.0 and 10.1, but I wrongly stated CUDA 10.1 in the readme. Sorry for the confusion. By the way, you can adapt it to newer version of pytorch if necessary.

**Comment by HMCCMH** [comment]
Hi DongSky,
    I find that your lbba.yaml use the scipy1.4.1, but the network.py use `from scipy.misc import imresize `. However, the version 1.4.1 can't support the  imresize function. I see that the imresize function was completely abandoned in the 1.3.0 version of scipy. So what actually you use in the environment?

**Comment by DongSky** [comment]
> 

We use scipy == 1.1.0. 
Sorry I'm not sure why anaconda exported a newer version into the lbba.yml. A possible reason is that the packages installed by pip may cover the originally installed packages from anaconda, but cannot be detected by conda package manager.  Sincerely sorry for the confusion.
